services:
  - type: web
    name: potato-disease-backend
    env: python
    plan: free
    runtime: python-3.10
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    rootDir: backend
